- hosts: local
  become: yes #Escala privilégios
  tasks:
    - name: Atualizar repositórios apt
      apt:
        update_cache: yes

    - name: Instalar pacotes necessários para o Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Adicionar chave GPG oficial do Docker
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    
    - name: Adicionar repositório Docker APT
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Atualizar repositório após adicionar Docker
      apt:
        update_cache: yes

    - name: Instalar Docker CE
      apt:
        name: docker-ce
        state: latest

    - name: Adicionar usuário ao grupo Docker (sem preciar de sudo)
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Habilitar e iniciar serviço Docker
      service:
        name: docker
        state: started
        enabled: yes
