- hosts: localhost
  become: yes
  environment:
    KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
  tasks:
    - name: Criar o namespace 'database' para PostgreSQL
      shell: kubectl create namespace database
      ignore_errors: yes

    - name: Criar Secret para credenciais do PostgreSQL (somente username e password)
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: postgres-secret
          namespace: database
        type: Opaque
        data:
          POSTGRESQL_USERNAME: cG9zdGdyZXM=
          POSTGRESQL_PASSWORD: MTIz
        EOF

    - name: Criar ConfigMap para o PostgreSQL (contém apenas o database)
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: postgres-config
          namespace: database
        data:
          POSTGRESQL_DATABASE: "kollabio"
        EOF
