- name: Remoção do ambiente WSL e pacotes instalados
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Parar e deletar Minikube
      shell: minikube delete
      ignore_errors: true

    - name: Remover pacotes instalados
      apt:
        name: ['docker-ce', 'curl', 'apt-transport-https', 'ca-certificates', 'software-properties-common']
        state: absent
      ignore_errors: true

    - name: Limpar arquivos de configuração
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/bin/minikube
        - /usr/local/bin/kubectl